"""create Role model

Revision ID: c1d33c1a5ee3
Revises: 11d198e03150
Create Date: 2024-07-16 23:26:40.980636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d33c1a5ee3'
down_revision = '11d198e03150'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('auditions', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_auditions_role_id_roles'), 'auditions', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_auditions_role_id_roles'), 'auditions', type_='foreignkey')
    op.drop_column('auditions', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
